project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

toc: true
toc-depth: 3
# bibliography: references.bib

book: 
  title: Study notebook for FACE
  author:
  - Sarah Sant'ana, MS
  site-url: https://github.io/jjcurtin/notes_face
  repo-url: https://github.com/jjcurtin/notes_face
  repo-branch: main
  repo-actions: [edit]
  sharing: [facebook, linkedin]
  page-navigation: true
  chapters:
    - index.qmd
    - data_structure.qmd
    - outcome_labels.qmd
    - study_sample.qmd
    - message_cleaning.qmd
    - part: "Feature Engineering"
      chapters: 
        - feat_overview.qmd
        - dictionaries.qmd
        - sentiment.qmd
        - topic_modeling.qmd
        - llms.qmd
        - tune_liwc.qmd
        - tune_emojis.qmd

    
