---
title: "Outcome Labels"
format: html
editor: visual
---

Primary classification labels of positive or negative AUD status were derived via in person administered SCIDs. These notes describe scoring decisions, subject notes, and data descrepancies identified in cleaning SCID data to generate the final outcome labels for face. Refer to mak_scid.Rmd for code used to identify cases

## Inputs

-   \_SS_SCID.csv files: One per subject. These are the graduate clinician's scoring of SCID audio recordings from sessions. These scores serve as the final outcome labels for SCID diagnoses
-   qualtrics_scid.csv: One aggregate file. Compiled responses of RA scid scores collected during session
-   \_NewSCID.xlsx files: Rescores of earlier scids by RAs due to updates made to scoring criteria during data collection. These files replace original qualtrics scores

## Outputs

### scid_labels.csv

Generated based on cleaning and combining all \_SS_SCID files.

Data Dictionary:

**subid**: Subject ID number ranging from 001 - 1047. ID number used to identify all subject data EXCEPT social media data

**se0**: SCID-V-Research Version Module E screening question (E1): Have you drank alcohol at least 6 times in the past 12 months? Answers: yes or no

**se1**: SCID-V-Research Version Module E question 1 (E2): Alcohol is often taken in larger amounts OR over a longer period than was intended. Answers: yes or no

**se2**: SCID-V-Research Version Module E question 2 (E3): There is a persistent desire OR unsuccessful efforts to cut down or control alcohol use. Answers: yes or no

**se3**: SCID-V-Research Version Module E question 3 (E4): A great deal of time is spent in activitiesnecessary to obtain alcohol, use alcohol, or recover from its effects. Answers: yes or no

**se4**: SCID-V-Research Version Module E question 4 (E5): Craving, or a strong desire or urge to use alcohol. Answers: yes or no

**se5**: SCID-V-Research Version Module E question 5 (E6): Recurrent alcohol use resulting in a failure to fulfill major role obligations at work, school, or home \[(e.g., repeated absences or poor work performance related to alcohol use; alcohol-related absences, suspensions, or expulsions from school; neglect of children or household)\]. Answers: yes or no

**se6**: SCID-V-Research Version Module E question 6 (E7): Continued alcohol use despite having persistent or recurrent social or interpersonal problems caused or exacerbated by the effects of alcohol \[(e.g., arguments with spouse about consequences of intoxication, physical fights)\]. Answeres: yes or no

**se7**: SCID-V-Research Version Module E question 7 (E8): Important social, occupational, or recreational activities given up or reduced because of alcohol use. Answers: yes or no

**se8**: SCID-V-Research Version Module E question 8 (E9): Recurrent alcohol use in situations in which it is physically hazardous \[(e.g., driving an automobile or operating a machine when impaired by alcohol use)\]. Answers: yes or no

**se9**: SCID-V-Research Version Module E question 9 (E10): Alcohol use is continued despite knowledge of having a persistent or recurrent physical or psychological problem that is likely to have been caused or exacerbated by alcohol \[(e.g., continued drinking despite recognition that an ulcer was made worse by alcohol consumption)\]. Answers: yes or no

**se10**: SCID-V-Research Version Module E question 10 (E11): Tolerance, as defined by either of the following: a. A need for markedly increased amounts of alcohol to achieve intoxication or desired effect. b. Markedly diminished effect with continued use of the same amount of alcohol. Answers: yes or no

**se11**: SCID-V-Research Version Module E question 11 (E12): Withdrawal, as manifested by either of the following: a. At least TWO of the following developing within several hours to a few days after the cessation of (or reduction in) alcohol use: autonomic hyperactivity (e.g., sweating or pulse rate greater than 100 bpm), increased hand tremor, insomnia, nausea or vomiting, psychomotor agitation, anxiety, generalized tonic-clonic seizures, transient visual, tactile, or auditory hallucinations or illusions b. Alcohol (or a closely related substance such as a benzodiazepine) is taken to relieve or avoid withdrawal symptoms. Answers: yes or no

**total**: The total count of "yes" responses for a participant on items se1 - se11. Possible range: 0 - 11. Total calculated in mak_scid.Rmd

**aud**: A binary positive/negative variable indicating if a participant is positive or negative for Alcohol Use Disorder. Presence of 2 or more symptoms (total variable \>= 2) results in a positive label

**severity**: A four level factor denoting the severity of alcohol use disorder. Levlels are: Negative (Participant does not meet criteria for AUD, total score \<=1), Mild (total score = 2 or 3), Moderate (total score = 4 or 5), and Severe (total score \>= 6).

### Interrater reliability

Generated based on comparing \_SS_SCID scores with RA scores from qualtrics (or \_NewSCID) files

Data Dictionary:

Same as above, but also including ra scores (ra variables are preceded by "ra\_" e.g. ra_se0, ra_se1...)SCID Cleaning notes

## \_SS_SCID files -\> final labels

-   Three subjects (092, 412, 509) were missing SCID audio recordings and could not be independently scored by Sarah. \_SCID_SS scoring files for these three participants are copies of the qualtrics responses for these sessions. Questions: Should I delete SS files for these and just fill them in from qualtrics in cleaning? How to handle these in reliability analysis?

-   Sarah did not always enter Total Scores in spreadsheet. This variable was instead calculated in mak_scid.Rmd

-   All SS files were confirmed to use correct scoring (1, 3) recoded to yes/no for each symptom in cleaning

## Qualtrics and new_scid files

### Data type errors

-   Subid 754. RA reported they incorrectly entered survey as fake/training data during real session. Updated to "Real"

### SubID errors

SubIDS entered as SMIDS (corrected to subid by looking up match in id_xlsx) \* 285953 corrected to 292 \* 668698 corrected to 375 \* 165500 corrected to 410 \* 913773 corrected to 482 \* 285953 corrected to 292 \* 668698 corrected to 375 \* 165500 corrected to 410 \* 913773 corrected to 482

Duplicate subids. Corrections to find true subid for sessions was done by matching session time, calendar session, RA notes, and ID tracker. All corrections done by SS

-   870 (not real subid) corrected to 863
-   029 with start_date=="2018-06-08 19:52:58" corrected to 026
-   325 with start_date=="2018-08-31 17:28:55" corrected to 320
-   723 with start_date=="2019-03-15 17:24:12"corrected to 727

### Invalid responses

6 qualtrics surveys had answers that were not 1 or 3. For all 7 cases with invalid responses, SS reviewed SCID scoring protocol document and scored these items as 1 or 3

\`\`\`
